
### Spring Properties
spring:
  application:
    name: pres
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  # MySQL Server datasource Properties
  datasource:
    url: jdbc:mysql://localhost:3306/test_containers_test
    username: root
    password: 'Test#12345'
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA properties
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        ddl-auto: update
        show_sql: true
        generate_statistics: false
